-- This CLP file was created using DB2LOOK Version "10.5" 
-- Timestamp: Sat May 14 14:55:07 2022
-- Database Name: SAMPLE         
-- Database Manager Version: DB2/LINUXX8664 Version 10.5.7 
-- Database Codepage: 1208
-- Database Collating Sequence is: IDENTITY
-- Alternate collating sequence(alt_collate): null
-- varchar2 compatibility(varchar2_compat): OFF


CONNECT TO SAMPLE;

--------------------------
-- Mimic Storage groups --
--------------------------
 
ALTER STOGROUP "IBMSTOGROUP"
	 OVERHEAD 6.725000
	 DEVICE READ RATE 100.000000
	 DATA TAG NONE 
	 SET AS DEFAULT;

------------------------------------
-- DDL Statements for TABLESPACES --
------------------------------------


CREATE LARGE TABLESPACE "IBMDB2SAMPLEREL" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 8192 MANAGED BY AUTOMATIC STORAGE 
	 USING STOGROUP "IBMSTOGROUP" 
	 AUTORESIZE YES 
	 INITIALSIZE 32 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 32
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL "IBMDEFAULTBP"
	 DATA TAG INHERIT
	 OVERHEAD INHERIT
	 TRANSFERRATE INHERIT 
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "IBMDB2SAMPLEXML" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP 
	 PAGESIZE 8192 MANAGED BY AUTOMATIC STORAGE 
	 USING STOGROUP "IBMSTOGROUP" 
	 AUTORESIZE YES 
	 INITIALSIZE 32 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 32
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL "IBMDEFAULTBP"
	 DATA TAG INHERIT
	 OVERHEAD INHERIT
	 TRANSFERRATE INHERIT 
	 DROPPED TABLE RECOVERY ON;


CREATE LARGE TABLESPACE "SYSTOOLSPACE" IN DATABASE PARTITION GROUP IBMCATGROUP 
	 PAGESIZE 8192 MANAGED BY AUTOMATIC STORAGE 
	 USING STOGROUP "IBMSTOGROUP" 
	 AUTORESIZE YES 
	 INITIALSIZE 32 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 4
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL "IBMDEFAULTBP"
	 DATA TAG INHERIT
	 OVERHEAD INHERIT
	 TRANSFERRATE INHERIT 
	 DROPPED TABLE RECOVERY ON;


----------------------
-- Mimic tablespace --
----------------------

ALTER TABLESPACE "SYSCATSPACE"
      PREFETCHSIZE AUTOMATIC
      OVERHEAD INHERIT
      AUTORESIZE YES 
      TRANSFERRATE INHERIT;


ALTER TABLESPACE "SYSCATSPACE"
      USING STOGROUP "IBMSTOGROUP"; 


ALTER TABLESPACE "TEMPSPACE1"
      PREFETCHSIZE AUTOMATIC
      OVERHEAD INHERIT
      FILE SYSTEM CACHING 
      TRANSFERRATE INHERIT;


ALTER TABLESPACE "USERSPACE1"
      PREFETCHSIZE AUTOMATIC
      OVERHEAD INHERIT
      AUTORESIZE YES 
      TRANSFERRATE INHERIT
      DATA TAG INHERIT;


ALTER TABLESPACE "USERSPACE1"
      USING STOGROUP "IBMSTOGROUP"; 


COMMIT WORK;

CONNECT RESET;

TERMINATE;

